### ISSUE TITLE
NODE_PATH not being obeyed

### ISSUE THREAD

**Issue by brandonros** [istanbuljs/append-transform#13]
```
$ NODE_PATH="./mac" JASMINE_CONFIG_PATH=./test/jasmine.unit.json ./mac/node_modules/.bin/nyc ./mac/node_modules/.bin/jasmine-ts "test/unit/**/*.spec.ts"
Error: dlopen(/Users/bros/repos/node-sso-formatter/node_modules/heapdump/build/Release/addon.node, 1): no suitable image found.  Did find:
	/Users/bros/repos/node-sso-formatter/node_modules/heapdump/build/Release/addon.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/bros/repos/node-sso-formatter/node_modules/heapdump/build/Release/addon.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/bros/repos/node-sso-formatter/node_modules/heapdump/index.js:16:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module.replacementCompile (/Users/bros/repos/node-sso-formatter/mac/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.<anonymous> (/Users/bros/repos/node-sso-formatter/mac/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

```
$ node -v
v10.15.0
```

**Comment by brandonros** [comment]
node.js internal modle loader starts off obeying NODE_PATH="./mac" but it seems when `append-transform` goes to include the native node.js module for `heapdump`, it uses an incorrect path (ignores NODE_PATH)

**Comment by brandonros** [comment]
This is a `typescript` problem.
